app_monitoring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('auth/', include('authentication.urls', namespace='authentication')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('monitor/', include('monitor.urls', namespace='monitor')),
    path('sensordata/', include('sensor_data.urls', namespace='sensor_data')),
]

authentication/urls.py
from django.urls import path

from . import views

app_name = 'authentication'

urlpatterns = [
    path('logout/', views.logout, name='logout'),
]

core/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('products', views.products, name='products'),
]

monitor/urls.py
from django.urls import path

from . import views

app_name = 'monitor'

urlpatterns = [
    path('variables/', views.variables, name='variables'),
    path('tracking/', views.tracking, name='tracking'),
]

sensor_data/urls.py
from django.urls import path

from . import views
from . import constants

app_name = 'sensor_data'

urlpatterns = [
    path(constants.CLEAN_DATA, views.clean_data, name='clean_data'),
    path(constants.GET_LATEST, views.get_latest, name='get_latest'),
    path(constants.CREATE_DATA, views.create_data, name='create_data'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def home(request):
    return render(request, 'statistics/indicators.html')

@login_required
def products(request):
    return render(request, 'core/products.html')

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    {% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Proyecto ENA</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <!-- Bloque para styles adicionales -->
    {% block styles %}{% endblock %}
  </head>
  <body class="container">
    <header>
      <h1>Proyecto ENA</h1>
    </header>
    <nav class="sidebar">
      <article class="logo">
        <h2>Proyecto ENA</h2>
      </article>
      <ul>
        <li><a href="{% url 'home' %}">Inicio</a></li>
        <li>
          <a href="{% url 'monitor:variables' %}">Monitoreo de Variables</a>
        </li>
        <li><a href="{% url 'monitor:tracking' %}">Vista Mapa</a></li>

        {% if request.user.is_superuser %}
        <li><a href="{% url 'sensor_data:clean_data' %}">Limpiar Datos</a></li>
        {% endif %}
      </ul>
    </nav>

    <div class="user-info">
      {% if request.user.is_authenticated %}
      <p>Hola, {{ user.username }}</p>
      <a class="logout" href="{% url 'authentication:logout' %}">Salir</a>
      {% endif %}
    </div>

    <main class="main-content">{% block content %} {% endblock %}</main>
  </body>
  <!-- Bloque para scripts adicionales -->
  {% block scripts %}{% endblock %}
</html>