app_monitoring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('auth/', include('authentication.urls', namespace='authentication')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('monitor/', include('monitor.urls', namespace='monitor')),
    path('sensordata/', include('sensor_data.urls', namespace='sensor_data')),
]

core/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('products', views.products, name='products'),
]

monitor/urls.py
from django.urls import path

from . import views

app_name = 'monitor'

urlpatterns = [
    path('variables/', views.variables, name='variables'),
    path('tracking/', views.tracking, name='tracking'),
]

sensor_data/urls.py
from django.urls import path

from . import views
from . import constants

app_name = 'sensor_data'

urlpatterns = [
    path(constants.CLEAN_DATA, views.clean_data, name='clean_data'),
    path(constants.GET_LATEST, views.get_latest, name='get_latest'),
    path(constants.CREATE_DATA, views.create_data, name='create_data'),
]

monitor/models.py
from django.db import models

# Create your models here.

monitor/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

context = {
    'update_interval': 4000,  # Intervalo en milisegundos (1000 ms = 1 segundo)
}

@login_required
def variables(request):
    return render(request, 'variables/variables.html', context)

@login_required
def tracking(request):
    return render(request, 'tracking/tracking.html', context)

monitor/templates/tracking/tracking.html
{% extends "core/base.html" %}
{% load static %}

{% block styles %}
<link
  rel="stylesheet"
  href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
/>
{% endblock %}

{% block content %}

<header class="header">
  <h1>Mapa de Monitoreo</h1>
</header>

<section id="map"></section>

{% endblock %}

{% block scripts %}
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
<script src="{% static 'js/tracking.js' %}"></script>
<script>
  const UPDATE_INTERVAL = {{ update_interval }};
  const GET_LATEST_SENSOR_DATA_URL = "{% url 'sensor_data:get_latest' %}";
</script>
{% endblock %}